### PR TITLE
Migrate SSML to new package

### PR DESCRIPTION
**Pull request by harrisonhjones**
# Overview

- Migrate the current SSML builder to a new `ssml` package (see #22)
- Wrote tests with 100% coverage
- Would ideally pull this into a development branch but I'm unsure how to do that on GitHub

# Details

- Migrate the current SSML builder to a new `ssml` package (see #22)
- Broke up types into separate packages
- Refactored any functions which take `text` as an argument to take `text` as the last argument
- Refactored all builder functions to return the builder and an error for future expansion / parameter checking

# Testing

- 100% unit tests of `ssml` package

# TODO

- Builder function parameter validation
- Support for more SSML features
- Migrate the `skillbuilder` to use this
- Deprecate old `ssml` functions in the `skillbuilder` package

### CODE REVIEW

**Comment by rking788** [comment]
I think its probably required for @mikeflynn to create a devel branch on his repository and then recreating the pull request to that branch instead of master. I'm not sure if you can modify the destination of a pull request after it is created.

**Comment by mikeflynn** [comment]
I just created a `PR-13` branch from the current `master`.

**Comment by harrisonhjones** [comment]
@mikeflynn thanks. Since I plan on issuing several PRs and getting those reviewed before pulling it all into master can you create a more aptly named branch such as "package-refactor-dev"?

**Comment by rking788** [comment]
What is the intended benefit of breaking each of the SSML types into their own sub package? Is it meant to help keep applications small by only importing what is needed or do you think there will be enough code in each that it will be necessary to keep everything organized?

**Comment by harrisonhjones** [comment]
@rking788 a couple of reasons. It obviously could be in a single `types.go` but by grouping each type I feel it makes it more readable and potentially easier to test. As you mentioned it also helps with organization. As the Amazon team continues to add more SSML support the SSML package is going to get bigger. I would like for new features, tags, etc to being as compartmentalized as possible.

**Comment by mikeflynn** [comment]
@harrisonhjones The `package-refactor-dev` has been created.

**Comment by harrisonhjones** [comment]
Thanks @mikeflynn, created pull request #26

**Pull request closed without merging**
