### PR TITLE
Adding SSMLTextBuilder helper type to help build SSML strings.

### PR DESCRIPTION
**Pull request by rking788**
Convenience types and some methods to make it easier to build an SSML output string.

### CODE REVIEW

**Comment by rking788** [comment]
Here is a sample of what it would look like using this:

```
builder := skillserver.NewSSMLTextBuilder()
result := builder.
	AppendEmphasis("Some emphasis", "strong").
	AppendAmazonEffect("whisper it", "whispered").
	Build()

response := skillserver.NewEchoResponse()
response.OutputSpeechSSML(result)
```

**Comment by mikeflynn** [comment]
This is a cool idea. Can you break the SSMLTextBuilder code out in to it's own file just to keep things clean?

**Comment by rking788** [comment]
Ya i will go ahead and make that change. do you want all of the SSML stuff in that file? Like OutputSSML for example? or just the new SSMLTextBuilder stuff?

**Comment by mikeflynn** [comment]
I guess it probably makes sense to put all the SSML in there for consistency sake.

**Comment by rking788** [comment]
Split the SSML stuff into a new file. Added an append method for plain speech that could be used in between special effects.

**Comment by mikeflynn** [comment]
Don't kill me, but after reviewing this change now and I think we should leave your SSML builder code in one file and move the original SSML function back to `echo.go`. Happy to get other input, but I think that makes the most sense. Sorry for the change.

If you can put those two functions back, I'll merge this in.

**Comment by rking788** [comment]
Fixed. Does GitHub provide an option to squash commits when merging them in? I guess I should have done that on my side maybe.

**Comment by rking788** [comment]
Any other changes you would like to be made?

**Comment by mikeflynn** [comment]
Looks good. Merging in.

**Pull request merged**
