### PR TITLE
Start adding support for dialogs.

### PR DESCRIPTION
**Pull request by rking788**
Added code to start supporting dialogs.
Added constant string values for the dialogState property.
Added new methods for appending directives to the Echo response.

### CODE REVIEW

**Comment by rking788** [comment]
Working on addressing #19 .

**Comment by mikeflynn** [comment]
I'm not up to date on the whole dialogs addition. I'll try to review so I can get up to speed on this and effectively check this change.

(I've been out of touch with the latest in Alexa development, but I have a project idea I've been meaning to start on soon. However, if someone else, ideally someone who uses the library for production projects regularly, would like to join me in managing this project, that would be great.)

**Comment by rking788** [comment]
Issue #19 has a link to the Alexa skill reference for dialogs. The most straight forward part is just returning a directive for Dialog.Delegate which tells Alexa to use prompts defined in the interaction model until all slot values are filled. Dialog states are passed in as STARTED, IN_PROGRESS, or COMPLETE. So by returning Dialog.Delegate it will allow Alexa to continue prompting the user for slot values. This would be a good start to get people going. 

As a side note, I'm using this project as a part of my Guardian Helper skill that is for managing in-game inventory and other activity information for Destiny the game.

https://www.amazon.com/Rob-Guardian-Helper/dp/B0727QSTT9/ref=sr_1_1?ie=UTF8&qid=1507085984&sr=8-1&keywords=guardian+helper
https://github.com/rking788/guardian-helper

**Comment by sholzmayer** [comment]
I already implemented directives in [my forked repository](https://github.com/sholzmayer/go-alexa/commit/1bc48c00c127ceae41caa505b40033648569999d). It is already tested and in use.
Maybe you'll have a look. I could create a PR for that. IMHO the code is in a typed way with optional parameters much cleaner. 

BTW: In production, I don't use the given dialogs from the skill for slot filling - i provide my own using the outputSpeech parameter.

**Comment by rking788** [comment]
@sholzmayer it looks like there are some fields missing from your commit like the dialog state to indicate dialog completion. I think its also useful to have helper methods for constructing the directive structs similar to the way things are handled for OutputSpeech. I would say either you can add these things or I can just update this PR with the type safety you used in your commit.

**Comment by rking788** [comment]
Added new strong typing for the directives and the confirmation status/dialog state/dialog type fields in the previous commit.

**Comment by rking788** [comment]
Should this now be closed since #44 was merged? Are there any dialog features that we know are missing after that pull request @rohitggarg ?

**Comment by mikeflynn** [comment]
Good point. I'll leave this open for a few days if anyone wants to say their piece, but if not I'll close it.

**Comment by rohitggarg** [comment]
Hey Rob, I have taken clues from your pull request. I think you're the best judge, have I missed anything?

**Comment by rking788** [comment]
just took a look at #44 and it seems like all of the functionality is there, closing this now.

**Comment by mikeflynn** [comment]
Thanks.

**Pull request closed without merging**
