### PR TITLE
Migrate SSML to new package

### PR DESCRIPTION
**Pull request by harrisonhjones**
# Overview

- Migrate the current SSML builder to a new `ssml` package (see #22)
- Wrote tests with 100% coverage
- Would ideally pull this into a development branch but I'm unsure how to do that on GitHub

# Details

- Migrate the current SSML builder to a new `ssml` package (see #22)
- Broke up types into separate packages
- Refactored any functions which take `text` as an argument to take `text` as the last argument
- Refactored all builder functions to return the builder and an error for future expansion / parameter checking

# Testing

- 100% unit tests of `ssml` package

# TODO

- Builder function parameter validation
- Support for more SSML features
- Migrate the `skillbuilder` to use this
- Deprecate old `ssml` functions in the `skillbuilder` package

### CODE REVIEW

**Comment by harrisonhjones** [comment]
@mikeflynn just a ping to take a look at this when you have a chance.

Also you mentioned that you were looking for a co-maintainer. I'd be happy to help in that capacity if you are still interested in help.

**Comment by mikeflynn** [comment]
Ok, great! I wasn't sure if this was ready or not. I'll take a look.

Yes, I do think this project could be helped by a co-maintainer would can be engaged when I can't be. This project we've got going here is a good start to be sure!

**Comment by mikeflynn** [comment]
We'll have to figure out how to avoid breaking changes once the skillserver package is updated to use this and that updated SSML function params (there's a few options that can be discussed), but this change itself looks good.

**Comment by mikeflynn** [comment]
Lots of little commits, so I'm going to squash and merge this one.

**Pull request merged**
