### PR TITLE
Expose the logic for validating an Alexa request in a public function.

### PR DESCRIPTION
**Pull request by rking788**
This will make it possible for other projects to use the Alexa request validation code from the skillserver package even if they choose to use their own HTTP server/routing.

### CODE REVIEW

**Comment by rking788** [comment]
Is there any interest in getting this merged? Would anyone else find this useful for their project other than me?

**Comment by rking788** [comment]
@mikeflynn how do you feel about merging this change?

**Comment by mikeflynn** [comment]
Apologies for the delay. I'm reviewing the change now.

**Comment by mikeflynn** [comment]
Change looks good and is pretty straightforward. Merged in.

Thanks!

**Comment by rking788** [comment]
No worries. Thanks for the merge.

**Pull request merged**
